// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylpomvcmsxqyniwwudav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlscG9tdmNtc3hxeW5pd3d1ZGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMjEyNjcsImV4cCI6MjA1NjU5NzI2N30.6fK-dmJ3As-mxQwYuv2T2aujuJvfUHD5aPNxF1XT4YI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);